#macro CELL_WIDTH  64
#macro CELL_HEIGHT 64
#macro FLOOR -5
#macro WALL -6
#macro VOID -1
#macro VDOOR -7
#macro HDOOR -8
#macro TOTAL_ROOMS 15
#macro MROOM_WIDTH 11
#macro MROOM_HEIGHT 7
#macro OBSTACLE -9
#macro BVDOOR -10
#macro BHDOOR -11 